// <auto-generated />
using System;
using InvestigacionClinica.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvestigacionClinica.Migrations
{
    [DbContext(typeof(InvestigacionClinicaContext))]
    [Migration("20260430025351_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvestigacionClinica.Dominio.Investigacion", b =>
                {
                    b.Property<int>("IdInvestigacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInvestigacion"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("TipoEstudio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdInvestigacion");

                    b.ToTable("Investigacion");
                });

            modelBuilder.Entity("InvestigacionClinica.Dominio.Recoleccion", b =>
                {
                    b.Property<int>("IdRecoleccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRecoleccion"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoProtocolo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Fechafin")
                        .HasColumnType("date");

                    b.Property<int>("IdInvestigacion")
                        .HasColumnType("integer");

                    b.Property<int>("Total")
                        .HasColumnType("integer");

                    b.HasKey("IdRecoleccion");

                    b.HasIndex("IdInvestigacion");

                    b.ToTable("Recoleccion");
                });

            modelBuilder.Entity("InvestigacionClinica.Dominio.Recoleccion_Resultado", b =>
                {
                    b.Property<int>("IdRecoleccionDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRecoleccionDetalle"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaAsignacion")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaRegistro")
                        .HasColumnType("date");

                    b.Property<int>("IdRecoleccion")
                        .HasColumnType("integer");

                    b.Property<int>("IdResultado")
                        .HasColumnType("integer");

                    b.HasKey("IdRecoleccionDetalle");

                    b.HasIndex("IdRecoleccion");

                    b.HasIndex("IdResultado");

                    b.ToTable("Recoleccion_Resultado");
                });

            modelBuilder.Entity("InvestigacionClinica.Dominio.Resultado", b =>
                {
                    b.Property<int>("IdResultado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdResultado"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoOrdenLaboratorio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoPaciente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaRecepcion")
                        .HasColumnType("date");

                    b.Property<string>("TieneValorAnormal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoPrueba")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValorObtenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdResultado");

                    b.ToTable("Resultado");
                });

            modelBuilder.Entity("InvestigacionClinica.Dominio.Resultado_Sintoma", b =>
                {
                    b.Property<int>("IdResultadoSintoma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdResultadoSintoma"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaRegistro")
                        .HasColumnType("date");

                    b.Property<int>("IdResultado")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoSintoma")
                        .HasColumnType("integer");

                    b.HasKey("IdResultadoSintoma");

                    b.HasIndex("IdResultado");

                    b.HasIndex("IdTipoSintoma");

                    b.ToTable("Resultado_Sintoma");
                });

            modelBuilder.Entity("InvestigacionClinica.Dominio.TipoSintoma", b =>
                {
                    b.Property<int>("IdTipoSintoma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoSintoma"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gravedad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdTipoSintoma");

                    b.ToTable("TipoSintoma");
                });

            modelBuilder.Entity("InvestigacionClinica.Dominio.Recoleccion", b =>
                {
                    b.HasOne("InvestigacionClinica.Dominio.Investigacion", "Investigacion")
                        .WithMany()
                        .HasForeignKey("IdInvestigacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investigacion");
                });

            modelBuilder.Entity("InvestigacionClinica.Dominio.Recoleccion_Resultado", b =>
                {
                    b.HasOne("InvestigacionClinica.Dominio.Recoleccion", "Recoleccion")
                        .WithMany()
                        .HasForeignKey("IdRecoleccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvestigacionClinica.Dominio.Resultado", "Resultado")
                        .WithMany()
                        .HasForeignKey("IdResultado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recoleccion");

                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("InvestigacionClinica.Dominio.Resultado_Sintoma", b =>
                {
                    b.HasOne("InvestigacionClinica.Dominio.Resultado", "Resultado")
                        .WithMany()
                        .HasForeignKey("IdResultado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvestigacionClinica.Dominio.TipoSintoma", "TipoSintoma")
                        .WithMany()
                        .HasForeignKey("IdTipoSintoma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resultado");

                    b.Navigation("TipoSintoma");
                });
#pragma warning restore 612, 618
        }
    }
}
